#pragma exclude_renderers gles3
#pragma kernel Main

#include "../Includes/CommonDataTypes.hlsl"

StructuredBuffer<PositionSample> _SrcBuffer;
int _BaseIndex;
int _InstanceCount;
int _DestOffset;

RWStructuredBuffer<PositionSample> _DestBuffer;

[numthreads(8, 1, 1)]
void Main(uint3 id: SV_DISPATCHTHREADID)
{
	int index = id.x + _BaseIndex;
	if (index >= _InstanceCount)
		return;

	PositionSample p = _SrcBuffer[index];
	_DestBuffer[index + _DestOffset] = p;
}
